accounts:
- darwin:
    baseUrl: "base_url"
- darwin:
    baseUrl: "base_url"
    basic:
      username: "username"
      password: "password"
- gitlab:
    baseUrl: "base_url"
    private:
      token: "token"
- gitlab:
    baseUrl: "base_url"
    oauth:
      token: "token"
- github:
    baseUrl: "base_url"
    uploadUrl: "upload_url"
- github:
    baseUrl: "base_url"
    uploadUrl: "upload_url"
    oauth2:
      token: "token"
      tokenType: "token_type"
      refreshToken: "refresh_token"
      expiry: "expiry"
- bitbucket:
    basic:
      username: "username"
      password: "password"
- bitbucket:
    oauth:
      token: "token"
      applicationId: "application_id"
