language: go

go:
- 1.11.x

env:
- GO111MODULE=on

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  # skip

script:
  - go get -t -v ./...
  - go vet ./...
  - go test -v -race ./...
  - mkdir bin
  # produce binaries for the common platforms, both amd64 and i386.
  # can't handle windows since it looks like it might need the fuse lib.
  - gox -os="linux darwin" -arch="amd64 386" -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" ./...
  # special build for linux arm systems, both 32 and 64 bit.
  # can't build arm64 yet. some code seems to allude to it, but the gox tool still reports an error.
  - gox -os="linux" -arch="arm" -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" ./...
